### PR TITLE
(Beginner) Update README.md

### PR DESCRIPTION
**Pull request by GizDave**
1st Meeting PR

### CODE REVIEW

**Comment by AdamTheWizard** [comment]
Hey, has this been done? sorry, I'm new to this.

**Comment by GizDave** [comment]
What do you mean?

**Comment by AdamTheWizard** [comment]
Sorry, I commented on the wrong tab. This site is so confusing for a newbie! I'm just looking for anywhere I can help out with something simple and easy.

**Comment by GizDave** [comment]
No problem. I am still new tl the site too.

Try forking the target code
Edit your fork version
Submit the changes through pull request
I think...

**Comment by AdamTheWizard** [comment]
Yeah thats literally all I needed to know for now, man. Much appreciated.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Pull request merged**
